name: CI

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "your_name"
          git config user.email "your_email@email.com"

      - name: Run script
        run: |
          echo "" >> README.md
          git add README.md
          git commit -m "Always Green!"

      - name: Push changes
        run: |
          git push https://<your_username>:${{ secrets.PAT_TOKEN }}@github.com/<your_username>/<your_repo>.git
