name: CI

on:
  schedule:
    - cron: '0 */2 * * *' # Runs every 2 hours
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run script
        run: |
          echo "" >> README.md
          git config user.name "your_name"
          git config user.email "your_email@email.com"
          git add README.md
          git commit -m "Always Green!"
          git push
